// <auto-generated />
using ConsoleAppHomework09;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleAppHomework09.Migrations
{
    [DbContext(typeof(OrderDataContext))]
    [Migration("20210630172008_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("ConsoleAppHomework09.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("ConsoleAppHomework09.Order", b =>
                {
                    b.OwnsOne("ConsoleAppHomework09.OrderDetails", "orderDetails", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("OrderAmount")
                                .HasColumnType("REAL");

                            b1.Property<string>("OrderName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("OrderUserName")
                                .HasColumnType("TEXT");

                            b1.HasKey("OrderId");

                            b1.ToTable("orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("orderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
